# Generated by Django 5.0.3 on 2024-03-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snsmodel',
            old_name='good',
            new_name='like',
        ),
    ]
